language: go

before_install:
  - go get github.com/mattn/goveralls
  - go get -u github.com/golang/lint/golint

script:
  - go test github.com/BenchR267/lbd/...
  - $HOME/gopath/bin/goveralls -service=travis-ci

go:
  - 1.8
  